### ISSUE TITLE
Make multiple .cia files all at once?

### ISSUE THREAD

**Issue by SiriusVI87** [xprism1/ntool#1]
I have around 6.500 CDN folders.

Do you know of a way I can use a bluk command for ntool?

Example: I have the 6.500 folders somewhere on my pc:

3D After Burner II (USA)
2 Fast 4 Gnomz (USA)
...

Is There a way to make ntool look in each folder and make a .cia file from all the CDN folders at once?

Thank you!

**Comment by xprism1** [comment]
Closing this as OP has solved it with a batch script in https://github.com/xprism1/ntool/issues/2#issuecomment-1606151368
